# This workflow will install Python dependencies, run tests and lint.
# For more information see: https://docs.github.com/en/actions/how-tos/writing-workflows/building-and-testing/building-and-testing-python

name: Test Python application

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install base deps
        run: python -m pip install -r requirements.txt

      - name: Install dev deps (if present)
        if: ${{ hashFiles('requirements_dev.txt') != '' }}
        run: python -m pip install -r requirements_dev.txt

      - name: Lint with ruff
        run: |
          ruff check --select=E9,F63,F7,F82
          ruff check --exit-zero --statistics

      - name: Install project
        run: pip install .

      - name: Run tests
        run: pytest
